### ISSUE TITLE
Network Policy feature Regression in the master branch

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#1190]
@dcbw @danwinship @dceara  looks like we have regressed NetworkPolicy feature in the master.

This is the commit that has regressed the repo.
--------8<---------8<-------
commit 591245645e8313dd458525bb8d2b2c952ff230ce
Author: Dumitru Ceara <dceara@redhat.com>
Date:   Wed Mar 25 14:15:22 2020 +0100

    ovn: Fix default deny ACLs.
    
    Deny ACLs for PolicyTypeEgress policies should be applied in direction
    "from-lport". Also, make the "find ACL" ovn-nbctl calls more specific by
    matching on direction and priority too.
    
    Fixes #1174.
    
    Signed-off-by: Dumitru Ceara <dceara@redhat.com>
--------8<---------8<-------

We cannot use `from-lport` direction as the ACLs are applied on the `ingress` pipeline of the switch even before LB has done its job. So, this will fail for Cluster IPs. See PR #370  for more info.
We will need to revert his commit. Thanks.

**Comment by dceara** [comment]
@girishmg, sorry about this.

Now I see that the "allow" ACLs are added in the egress pipeline of the logical switch (`localPodAddACL()` => `addACLAllow()`) and not in the ingress pipeline. I had missed that and the fact that the ingress ACLs are applied before LB.

Thanks for spotting this quickly,
Dumitru

**Comment by trozet** [comment]
How did our E2E tests not fail for this?

**Comment by trozet** [comment]
@girishmg can you comment on what test caught this in your suite?

**Comment by girishmg** [comment]
@trozet i have a simple two-tiered webapp -- web <--> mysql and the `web` connects to `mysql` using a Cluster IP. I have bunch of ACLs to allow traffic on certain ports. This failed for me.

**Comment by trozet** [comment]
@girishmg so just a simple cluster ip service...we should have hit this in our e2e. I'll try to investigate.

**Comment by trozet** [comment]
@girishmg I see that in the original patch this test passed:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/network_policy.go#L516

That is specifying policy with port and connecting to service. Although that policy is using ingress direction. Can you comment what your policy looked like in your test that failed? Thanks.

**Comment by girishmg** [comment]
@trozet this is what I have

```
# define network policies between the Web and Mysql Pods

# only Web pods should be able to access the mysql pod at port 3306
# drop all the egress traffic from mysql pod
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-mysql
spec:
  podSelector:
    matchLabels:
      name: mysql
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            name: web
      ports:
        - protocol: TCP
          port: 3306

---
# only
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-web
spec:
  podSelector:
    matchLabels:
      name: web
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
      - podSelector: {}
      ports:
        - protocol: TCP
          port: 5000
    - from:
      - ipBlock:
          cidr: 100.64.0.0/16
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
      - podSelector:
          matchLabels:
            name: mysql
      ports:
        - protocol: TCP
          port: 3306
    - to:
      # for DNS
      - namespaceSelector:
          matchLabels:
            name: kube-system
      ports:
        - protocol: UDP
          port: 53
```
