### ISSUE TITLE
[Help] How to add external node to the cluster using OVN-Kubernetes CNI Plugin.

### ISSUE THREAD

**Issue by nandakishorepeddi** [ovn-org/ovn-kubernetes#1693]
I am using Openshift container Platform 4.5, I migrated from default Openshift-SDN CNI plugin to OVN-Kubernetes CNI.
But I would like to add new external nodes (machines) as the endpoints to my OCP (openshift) cluster as a dummy node to add as an endpoint. So this external nodes can access the pods directly using GENEVE Protocol. This i used to do earlier with openshift-sdn by adding the hostsubnet. I tried add this using the below Yaml. But didnt work out to me. Could you please help me out on this. Did i miss anything (or) any other annotations?
Note : External host here is the load balancer, where it cannot run any docker images/ovnkube/ovnmaster. But this external host has the capability to create the geneve tunnel.

Tried the below node yaml:
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    k8s.ovn.org/node-mgmt-port-mac-address: xx:xx:xx:04:79:d1
    k8s.ovn.org/node-subnets: '{"default":"10.xxx.xxx.0/31"}'
  name: external_host
spec:
  podCIDR: 10.xxx.xxx.0/31
  podCIDRs:
  - 10.xxx.xxx.0/31
```
eg: Adding external host using Openshift-SDN (which worked earlier and added as an endpoint for VxLAN tunnel)
```
host: external_host
hostIP: 1x.x.x.x
kind: HostSubnet
metadata:
  annotations:
    pod.network.openshift.io/fixed-vnid-host: "0"
  name: external_host
  selfLink: /apis/network.openshift.io/v1/hostsubnets/bigip
subnet: 10.xxx.xxx.0/31
```
