### ISSUE TITLE
No validation of dnsName for egressFirewallDNS

### ISSUE THREAD

**Issue by JacobTanenbaum** [ovn-org/ovn-kubernetes#1929]
there is no validation for the dnsName in egressFirewall. I am not really sure how we want to deal with this I am putting it here so I don't loose track of the work. 

There are two issues that I can see and feel free to add any more 

- [ ] while not an issue unless it resolves to anything there is nothing preventing from adding DNS names that share namespace names which will cause the egressFirewall to put IP addresses in the namespace's address set (if it can resolve)  
- [ ] there is nothing to determine that "www.google.com" and "google.com" will be functionally the same thing, which would save some time on the DNS resolution side.

if I think of more or they get added in conversation I will add them to this list.

below will cause the egressFirewallDNS resolver to reuse the address set of the default namespace
```
kind: EgressFirewall                                                                                                                                                                                                                                                            
apiVersion: k8s.ovn.org/v1                                                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                                                       
  name: default                                                                                                                                                                                                                                                                 
spec:                                                                                                                                                                                                                                                                           
  egress:                                                                                                                                                                                                                                                                       
  - type: Allow                                                                                                                                                                                                                                                                 
    to:                                                                                                                                                                                                                                                                         
      dnsName: default                                                                                                                                                                                                                                     
  - type: Deny                                                                                                                                                                                                                                                                  
    to:                                                                                                                                                                                                                                                                         
      cidrSelector: 0.0.0.0/0 
```
