### ISSUE TITLE
External GW: Adding an ipv6 address as external ip is not working

### ISSUE THREAD

**Issue by fedepaol** [ovn-org/ovn-kubernetes#2012]
Found this while extending the external gw e2e test.

Narrowed reproducer:

- Setup a dual stack kind cluster
- Create a container on the same kind network
`docker run -itd --privileged --network kind --name ipv6target centos/tools`
- Take it's ipv6 address:
`docker inspect ipv6target -f {{range .NetworkSettings.Networks}}{{.GlobalIPv6Address}}{{end}} `

Create a ns:
kubectl create ns test

Create a pod in that ns
```
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: test
  labels:
    app: client
spec:
  containers:
    - name: client
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        ["sleep INF"]
```

Try to ping the ipv6 address from the pod: 
`kubectl exec -n test client -- ping fc00:f853:ccd:e793::5`

it works

Now annotate the namespace with the gateway annotation pointing to that pod:
`kubectl annotate ns test k8s.ovn.org/routing-external-gws=fc00:f853:ccd:e793::5`

The pod can't ping the container anymore.

If we create the namespace with the annotation and THEN we create the pod, the pod remains in pending.
