### ISSUE TITLE
All nodes send arp responses for external ip

### ISSUE THREAD

**Issue by codecap** [ovn-org/ovn-kubernetes#2853]
According to the [Documentation](https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/external-ip-and-loadbalancer-ingress.md) OVNKubernetes wont send answers to ARP requests toVIPs.

But this is what we can observe in our environment right now.

We have a small OKD 4.9 Cluster with 8 Nodes:
```
NAME                         STATUS   ROLES          AGE    VERSION
dev-clhpm-infra-main-9vtxs   Ready    infra,worker   14d    v1.22.3+e790d7f
dev-clhpm-infra-main-jl6ds   Ready    infra,worker   19d    v1.22.3+e790d7f
dev-clhpm-master-0           Ready    master         35d    v1.22.3+e790d7f
dev-clhpm-master-1           Ready    master         35d    v1.22.3+e790d7f
dev-clhpm-master-2           Ready    master         35d    v1.22.3+e790d7f
dev-clhpm-worker-sm9xk       Ready    worker         2d3h   v1.22.3+e790d7f
dev-clhpm-worker-wplh4       Ready    worker         5d3h   v1.22.3+e790d7f
dev-clhpm-worker-x2cd5       Ready    worker         2d3h   v1.22.3+e790d7f
```

OKD Version
```
Server Version: 4.9.0-0.okd-2022-01-14-230113
Kubernetes Version: v1.22.1-1827+e790d7fa218bce-dirty
```

OVNVersion
```
ovn-nbctl --version
ovn-nbctl 21.09.1
Open vSwitch Library 2.16.90
DB Schema 5.32.1

ovnkube --version
I0309 13:27:31.699796      80 ovs.go:98] Maximum command line arguments set to: 191102
Version: 0.3.0
Git commit: 87d25f1cefdb7bed3d11c7e42ad59c7f94d0709b
Git branch: release-4.9
Go version: go1.16.6
Build date: 2022-01-13
OS/Arch: linux amd64
```

Node Network: X.Y.Z.0/24
```
apiVersion: config.openshift.io/v1
kind: Network
metadata:
  generation: 3
    manager: kubectl-edit
  name: cluster
spec:
  clusterNetwork:
  - cidr: 172.22.0.0/17
    hostPrefix: 24
  externalIP:
    autoAssignCIDRs:
    - X.Y.Z.32/28
    policy:
      allowedCIDRs:
      - X.Y.Z.48/28
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.22.128.0/20
```

After we create a Service Type LoadBalancer
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-vnalb
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalIPs:
  - XY.Z.41
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
```

we try to *arping* the external IP:
```
arping -b X.Y.Z.39
ARPING X.Y.Z.39 from X.Y.Z.64 eth0
Unicast reply from X.Y.Z.39 [00:50:56:B3:7D:AD]  1.272ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:78:E1]  1.296ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:0E:7A]  1.307ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:FF:F4]  1.318ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:A4:27]  1.324ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:8C:5F]  1.331ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:D1:4C]  1.337ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:0E:7A]  1.361ms
Unicast reply from X.Y.Z.39 [00:50:56:B3:05:66]  1.367ms
```

The arping is send from a Machine, which is located within the Node Network, but doesn't belong to OKD cluster (was moved into the network for debugging)
