### ISSUE TITLE
failed to commit load balancer changes for map

### ISSUE THREAD

**Issue by codecap** [ovn-org/ovn-kubernetes#2854]
When creating a Service Type Load Balancer, ovnkube-master fails to configure Load Balancer for it
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-vnalb
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  #externalIPs:
  #- [EXTERNAL_IP]
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
```
In the log we see an error like  this
```
I0309 07:54:14.119528       1 services_controller.go:211] "Error syncing service, retrying" service="ingress-nginx/ingress-nginx-controller-test" err="failed to ensure service ingress-nginx/ingress-nginx-controller-test load balancers: failed to commit load balancer changes for map[string]string{\"k8s.ovn.org/kind\":\"Service\", \"k8s.ovn.org/owner\":\"ingress-nginx/ingress-nginx-controller-test\"}: OVN command '/usr/bin/ovn-nbctl --timeout=15 set load_balancer 52d004d9-f28a-4284-92da-86883217b3f1 external_ids:k8s.ovn.org/kind=Service external_ids:k8s.ovn.org/owner=ingress-nginx/ingress-nginx-controller-test name=Service_ingress-nginx/ingress-nginx-controller-test_TCP_cluster options:event=false options:reject=true options:skip_snat=false protocol=tcp selection_fields=[] vips={\"172.22.133.93:80\"=\"172.22.4.40:80,172.22.8.11:80\", ... , =\"172.22.4.40:443,172.22.8.11:443\"}' failed: exit status 1"
```
If we uncoment the line for externalIPs in the service and try again, it starts working.

I compared the /usr/bin/ovn-nbctl command, the difference is in the *vips* part, it addionally quoted then like
```
tcp selection_fields=[] "vips={\"172.22.133.93:80\"=\"172.22.4.40:80,172.22.8.11:80\", ... , =\"172.22.4.40:443,172.22.8.11:443\"}"'
```

OKD Version

```
Server Version: 4.9.0-0.okd-2022-01-14-230113
Kubernetes Version: v1.22.1-1827+e790d7fa218bce-dirty

```

OVNKubernetes Version

```
ovn-nbctl --version
ovn-nbctl 21.09.1
Open vSwitch Library 2.16.90
DB Schema 5.32.1

ovnkube --version
I0309 13:27:31.699796      80 ovs.go:98] Maximum command line arguments set to: 191102
Version: 0.3.0
Git commit: 87d25f1cefdb7bed3d11c7e42ad59c7f94d0709b
Git branch: release-4.9
Go version: go1.16.6
Build date: 2022-01-13
OS/Arch: linux amd64
```
