### ISSUE TITLE
multi-homed pods stuck in `ContainerCreating` 

### ISSUE THREAD

**Issue by maiqueb** [ovn-org/ovn-kubernetes#3428]
## Issue description
When creating pods referencing network-attachment-definitions (they may even be in different namespaces ...) pointing to the same network (via the net-attach-def.config `name` attribute) having **different** configurations (topology, for instance), all pods pointing at the last provisioned net-attach-def will hang in `ContainerCreating`.  Actually, only the pods pointing to the **first** network-attachment-definition will succeed.

This is the root cause for the flakes in the multi-homing lane (the namespace used for each test is randomized, but the tests all use the same network-attachment-definition name, and network name).

## Reproducing the issue
The issue is reproducing using this yaml:
```yaml
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bluenet
spec:
  config: |
    {                                                                           
      "cniVersion": "0.4.0",
      "name": "bluenet",
      "netAttachDefName": "default/bluenet",
      "topology": "layer2",
      "type": "ovn-k8s-cni-overlay",
      "subnets": "192.168.100.0/24",
      "logFile": "/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log",
      "logLevel": "5",
      "logfile-maxsize": 100,
      "logfile-maxbackups": 5,
      "logfile-maxage": 5
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: bluenet
spec:
  containers:
    - name: pod1
      image: k8s.gcr.io/e2e-test-images/agnhost:2.26
      command:
        - /bin/ash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
      securityContext:
        runAsUser: 1000
        privileged: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Namespace
metadata:
  name: ns1

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bluenet
  namespace: ns1
spec:
  config: |
    {                                                                           
      "cniVersion": "0.4.0",
      "name": "bluenet",
      "netAttachDefName": "ns1/bluenet",
      "topology": "layer3",
      "type": "ovn-k8s-cni-overlay",
      "subnets": "192.168.100.0/16/24",
      "logFile": "/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log",
      "logLevel": "5",
      "logfile-maxsize": 100,
      "logfile-maxbackups": 5,
      "logfile-maxage": 5
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: ns1
  annotations:
    k8s.v1.cni.cncf.io/networks: ns1/bluenet
spec:
  containers:
    - name: pod2
      image: k8s.gcr.io/e2e-test-images/agnhost:2.26
      command:
        - /bin/ash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
      securityContext:
        runAsUser: 1000
        privileged: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        allowPrivilegeEscalation: false
```
The second pod will hang indefinitely in `Pending` phase.

The following logs can be seen in ovnkube-master:
```
E0217 08:51:47.931606      74 network_attach_def_controller.go:358] Failed to add net-attach-def ns1/bluenet to network bluenet: NAD ns1/bluenet does not share the same CNI config with network bluenet
I0217 08:51:47.931721      74 network_attach_def_controller.go:213] Finished syncing net-attach-def ns1/bluenet : 608.498µs
W0217 08:51:47.931769      74 network_attach_def_controller.go:244] Dropping net-attach-def "ns1/bluenet" out of the queue: NAD ns1/bluenet does not share the same CNI config with network bluenet
```

## Workaround
PR #3422 addresses the e2e multi-homing flakes.

I think we can merge it, and leave this opened issue as a tracking artifact.
