### ISSUE TITLE
Cannot create routed secondary network with an IPv6 subnet

### ISSUE THREAD

**Issue by maiqueb** [ovn-org/ovn-kubernetes#3502]
Creating a secondary network with an IPv6 subnet fails.

Pods referring to the following net-attach-def fail to start:
```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: l3
spec:
    config: '{                                                                           
        "cniVersion": "0.4.0",
        "name": "l3",
        "netAttachDefName": "default/l3",
        "topology": "layer3",
        "type": "ovn-k8s-cni-overlay",                                          
        "subnets": "10:100:200::0/48/64", 
        "logFile": "/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log",           
        "logLevel": "5",                                                        
        "logfile-maxsize": 100,                                                 
        "logfile-maxbackups": 5,                                                
        "logfile-maxage": 5                                                     
    }'
```

The following log can be seen in ovnkube-master:
```
E0323 15:43:50.335552      58 obj_retry.go:623] Failed to update *v1.Node, old=ovn-worker2, new=ovn-worker2, error: nodeAdd: error adding node "ovn-worker2" for network l3: subnet annotation in the node "ovn-worker2" for the layer3 secondary network l3 is missing : node "ovn-worker2" has no "k8s.ovn.org/node-subnets" annotation for network l3
```

I wouldn't expect an IPv6 overlay to require the cluster to be configured w/ IPv6 service cidr or IPv6 network cidr.
