### ISSUE TITLE
Manually creating endpoints is broken in OVNK LBs

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#4123]
When manually creating the endpoints for a service like:
```
[trozet@fedora contrib]$ cat ~/service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: my-service1
  #namespace: exgw2
spec:
  #  selector:
  #    pod-name: server2        
  ports:
    - protocol: UDP
      port: 1337
      targetPort: 1337
      name: blah
    - protocol: TCP
      port: 80
      targetPort: 80
      name: blah2  
        #    - name: server-81
#      port: 81
#      protocol: TCP
#      targetPort: 81
#  externalIPs:
#    - 172.18.0.99
#  type: NodePort
  type: ClusterIP

[trozet@fedora contrib]$ cat ~/endpoint.yaml 
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service1
subsets:
  - addresses:
      - ip: 10.10.10.3
        #      - ip: 8.0.0.7
    ports:
      - port: 80

```

The endpoint wont actually be configured in the OVN LB:
[root@ovn-worker ~]# ovn-nbctl lr-lb-list GR_ovn-worker
UUID                                    LB                  PROTO      VIP                 IPs
f4edd556-172d-43e0-a525-615f9d7c5209    Service_default/    tcp        10.96.77.79:80      
20a472f6-d075-423d-9526-9cfd665f068b    Service_default/    udp        10.96.77.79:1337    

[trozet@fedora contrib]$ oc get service
NAME          TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)           AGE
kubernetes    ClusterIP   10.96.0.1     <none>        443/TCP           16m
my-service1   ClusterIP   10.96.77.79   <none>        1337/UDP,80/TCP   8m41s

[trozet@fedora contrib]$ oc get endpoints
NAME          ENDPOINTS         AGE
kubernetes    172.18.0.2:6443   17m
my-service1   10.10.10.3:80     6m11s

[trozet@fedora contrib]$ oc get endpointslice
NAME                ADDRESSTYPE   PORTS   ENDPOINTS    AGE
kubernetes          IPv4          6443    172.18.0.2   17m
my-service1-h6mx4   IPv4          80      10.10.10.3   6m14s
