### ISSUE TITLE
create address_sets only when required

### ISSUE THREAD

**Issue by girishmg** [ovn-org/ovn-kubernetes#718]
when we create a network policy for ingress (or egress) that contains only ipBlock fields and nothing else, for example like below:
```
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.10.0/24
        except:
        - 192.168.10.4/24
        - 192.168.10.7/24
  - from:
    - ipBlock:
        cidr: 192.168.1.0/24
        except:
        - 192.168.1.4/24
        - 192.168.1.7/24
  - from:
    - ipBlock:
        cidr: 192.168.0.0/24
        except:
        - 192.168.0.4/24
        - 192.168.0.7/24
```

we end up creating 3 address_sets (since 3 ingress rules) and they don't have any IP addresses

```
$ ovn-nbctl list address_set
_uuid               : d377d258-bbe5-49d5-bbf2-ed292395b869
addresses           : []
external_ids        : {name="default.ipblock-per-fromjson.ingress.2"}
name                : "a17551810608662632384"

_uuid               : 797df8ca-dee6-45f5-89d5-373f281d421b
addresses           : []
external_ids        : {name="default.ipblock-per-fromjson.ingress.0"}
name                : "a17551812807685888806"

_uuid               : 2da54dae-bf7a-4d36-a181-eff3cdb9d1ed
addresses           : []
external_ids        : {name="default.ipblock-per-fromjson.ingress.1"}
name                : "a17551813907197517017"
```
So, we should avoid creating the above 3 address_set.
